version : '3'

services:
  app:
    build:
      context: .
    ports:
      - 80:5000
    volumes:
      - ./app:/app

  website:
    image: httpd
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - app
